# Generated by Django 3.0.2 on 2020-01-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eng', models.CharField(max_length=255)),
                ('Viet', models.CharField(max_length=255)),
                ('pronunciation', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Engsssss',
            },
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
