# Generated by Django 2.2 on 2020-01-09 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
                ('idol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='idol.Idol')),
            ],
        ),
    ]
