sudo: false
dist: xenial
language: python
notifications:
  email: false
env:
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.15
  - DJANGO_VERSION=2.0.8
  - DJANGO_VERSION=2.1
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
matrix:
  exclude:
    - python: 2.7
      env: DJANGO_VERSION=2.0.8
    - python: 2.7
      env: DJANGO_VERSION=2.1
    - python: 3.5
      env: DJANGO_VERSION=1.6.11
    - python: 3.5
      env: DJANGO_VERSION=1.7.11
    - python: 3.5
      env: DJANGO_VERSION=1.8.18
    - python: 3.5
      env: DJANGO_VERSION=1.11.9
    - python: 3.6
      env: DJANGO_VERSION=1.6.11
    - python: 3.6
      env: DJANGO_VERSION=1.9.13
    - python: 3.6
      env: DJANGO_VERSION=1.10.8
    - python: 3.6
      env: DJANGO_VERSION=1.7.11
    - python: 3.7
      env: DJANGO_VERSION=1.8.18
    - python: 3.7
      env: DJANGO_VERSION=1.6.11
    - python: 3.7
      env: DJANGO_VERSION=1.9.13
    - python: 3.7
      env: DJANGO_VERSION=1.10.8
    - python: 3.7
      env: DJANGO_VERSION=1.7.11
    - python: 3.7
      env: DJANGO_VERSION=1.8.18
    - python: 3.7
      env: DJANGO_VERSION=1.11.15

stages:
  - lint
  - moban
  - test

.disable_global: &disable_global
  addons: false
  cache: false
  env: {}
  python: false
  before_install: false
  install: false
  before_script: false
  script: false
  after_success: false
  after_failure: false
  before_deploy: false
  deploy: false

.lint: &lint
  <<: *disable_global
  git:
    submodules: false
  python: 3.6
  stage: lint
  script: make lint

.moban: &moban
  <<: *disable_global
  python: 3.6
  stage: moban
  install: pip install moban>=0.0.4
  script:
    - moban
    - git diff --exit-code

jobs:
  include:
    - *moban
    - *lint

stage: test

before_install:
  - pip install Django==$DJANGO_VERSION
  - if [[ -f min_requirements.txt && "$MINREQ" -eq 1 ]]; then
      mv min_requirements.txt requirements.txt ;
    fi
  - test ! -f rnd_requirements.txt ||
    pip install --no-deps -r rnd_requirements.txt
  - test ! -f rnd_requirements.txt || pip install -r rnd_requirements.txt ;
  - pip install -r tests/requirements.txt
script:
  - make test
after_success:
  codecov
