"""
Django settings for caitaocanlacaiextensionmorongsaunay project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from caitaocanlacaiextensionmorongsaunay.TEMPLATES import TEMPLATES
from caitaocanlacaiextensionmorongsaunay.INSTALLED_APPS import INSTALLED_APPS
from caitaocanlacaiextensionmorongsaunay.MIDDLEWARE import MIDDLEWARE
from caitaocanlacaiextensionmorongsaunay.AUTH_PASSWORD_VALIDATORS import AUTH_PASSWORD_VALIDATORS
from caitaocanlacaiextensionmorongsaunay.DATABASES import DATABASES

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'gxa3&u723(oyagdq^cbd%3w4s7-d0i+#vy)!!9gd%gj@ezh1%*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


ROOT_URLCONF = 'caitaocanlacaiextensionmorongsaunay.urls'

FILE_UPLOAD_HANDLERS = ("django_excel.ExcelMemoryFileUploadHandler",
                        "django_excel.TemporaryExcelFileUploadHandler")

WSGI_APPLICATION = 'caitaocanlacaiextensionmorongsaunay.wsgi.application'

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
